AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/NestedParenthesizedCalls:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/ArgumentAlignment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
