#!/usr/bin/env ruby

require_relative './log_parser/env'

require 'log_parser/cli/options'
require 'log_parser/cli/run'

module LogParser
  module CLI
    options = Options.parse!(ARGV)
    Run.(options)
  end
end
